/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solitariochino;

import com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Result;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;

/**
 *
 * @author Manuel Manzano López.
 */
public class main extends javax.swing.JFrame {
    
    Solitaire solitariochino=new Solitaire(3);
   

    
        
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icon.png")).getImage() );
        this.setLocationRelativeTo(null);
        this.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        this.windowClosing();
        jToggleButtonposition.setSelected(false);
        jToggleButtonposition.setText("Inicial");
        jDialogsetting.setSize(500, 400);
        jLayeredPane2.setVisible(true);
        jDesktopPane1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogsetting = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxlevel = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButtonexamine1 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFramecreategame = new javax.swing.JInternalFrame();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenusettingmenu = new javax.swing.JMenu();
        jMenuItemnewgame1 = new javax.swing.JMenuItem();
        jMenuItemrefresh = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemundomenu = new javax.swing.JMenuItem();
        jMenuItemreundomenu = new javax.swing.JMenuItem();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonundo = new javax.swing.JButton();
        jButtonundo1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButtonmove = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldxin = new javax.swing.JTextField();
        jTextFieldyin = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldxout = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldyout = new javax.swing.JTextField();
        jPanelgamepad = new javax.swing.JPanel();
        jButtonleft = new javax.swing.JButton();
        jButtonup = new javax.swing.JButton();
        jButtonright = new javax.swing.JButton();
        jToggleButtonposition = new javax.swing.JToggleButton();
        jButtondown = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreadisplay = new javax.swing.JTextArea();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemopen = new javax.swing.JMenuItem();
        jMenuItemnewgame = new javax.swing.JMenuItem();
        jMenuItemexportxml = new javax.swing.JMenuItem();
        jMenuItemexit = new javax.swing.JMenuItem();
        jMenuedit = new javax.swing.JMenu();
        jMenuItemundo = new javax.swing.JMenuItem();
        jMenuItemreundo = new javax.swing.JMenuItem();
        jMenuItemmakegame = new javax.swing.JMenuItem();
        jMenusetting = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jDialogsetting.setPreferredSize(new java.awt.Dimension(100, 200));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));

        jComboBoxlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxlevelActionPerformed(evt);
            }
        });

        jLabel6.setText("Nivel:");

        jButtonexamine1.setText("Examinar...");
        jButtonexamine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexamine1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonexamine1)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonexamine1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Juego", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab2", jPanel5);

        jTabbedPane1.addTab("Personalización", jTabbedPane3);
        jTabbedPane1.addTab("Idioma", jTabbedPane4);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogsettingLayout = new javax.swing.GroupLayout(jDialogsetting.getContentPane());
        jDialogsetting.getContentPane().setLayout(jDialogsettingLayout);
        jDialogsettingLayout.setHorizontalGroup(
            jDialogsettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        jDialogsettingLayout.setVerticalGroup(
            jDialogsettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jInternalFramecreategame.setVisible(true);

        jToolBar1.setRollover(true);

        jButton3.setText("Cortar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setText("Copiar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setText("Pegar");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jScrollPane2.setViewportView(jTextPane1);

        jMenu6.setText("Archivo");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Editar");

        jMenuItem4.setText("jMenuItem4");
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        jMenu7.add(jMenuItem5);

        jMenuBar2.add(jMenu7);

        jMenu1.setText("Ver");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuItem7.setText("jMenuItem7");
        jMenu1.add(jMenuItem7);

        jMenuBar2.add(jMenu1);

        jInternalFramecreategame.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFramecreategameLayout = new javax.swing.GroupLayout(jInternalFramecreategame.getContentPane());
        jInternalFramecreategame.getContentPane().setLayout(jInternalFramecreategameLayout);
        jInternalFramecreategameLayout.setHorizontalGroup(
            jInternalFramecreategameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramecreategameLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 383, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramecreategameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jInternalFramecreategameLayout.setVerticalGroup(
            jInternalFramecreategameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramecreategameLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPopupMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenusettingmenu.setText("Opciones");
        jMenusettingmenu.setMinimumSize(new java.awt.Dimension(100, 100));
        jMenusettingmenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenusettingmenuFocusGained(evt);
            }
        });

        jMenuItemnewgame1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemnewgame1.setText("Nuevo");
        jMenuItemnewgame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemnewgame1ActionPerformed(evt);
            }
        });
        jMenusettingmenu.add(jMenuItemnewgame1);

        jMenuItemrefresh.setText("Actualizar");
        jMenuItemrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemrefreshActionPerformed(evt);
            }
        });
        jMenusettingmenu.add(jMenuItemrefresh);

        jMenuItem1.setText("Reiniciar");
        jMenusettingmenu.add(jMenuItem1);

        jPopupMenu1.add(jMenusettingmenu);

        jMenuItemundomenu.setText("Deshacer");
        jMenuItemundomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemundomenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemundomenu);

        jMenuItemreundomenu.setText("Rehacer");
        jMenuItemreundomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemreundomenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemreundomenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setComponentPopupMenu(jPopupMenu1);
        jPanel1.setOpaque(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/undo.png"))); // NOI18N
        jButtonundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonundoActionPerformed(evt);
            }
        });

        jButtonundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reundo.png"))); // NOI18N
        jButtonundo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonundo1ActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(0, 255, 0));
        jProgressBar1.setToolTipText("Progreso");
        jProgressBar1.setOpaque(true);
        jProgressBar1.setStringPainted(true);

        jButtonmove.setText("Mover");
        jButtonmove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmoveActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Posición Inicial"));

        jLabel1.setText("X in:");

        jLabel3.setText("Y in:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldxin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldyin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldyin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldxin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Posición final"));

        jLabel4.setText("X out:");

        jLabel5.setText("Y out:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldxout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldyout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldxout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldyout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonmove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonundo1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonundo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonundo1)
                    .addComponent(jButtonundo))
                .addGap(131, 131, 131)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonmove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelgamepad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelgamepad.setOpaque(false);

        jButtonleft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left.png"))); // NOI18N
        jButtonleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonleftActionPerformed(evt);
            }
        });

        jButtonup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/up.png"))); // NOI18N
        jButtonup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupActionPerformed(evt);
            }
        });

        jButtonright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/right.png"))); // NOI18N
        jButtonright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrightActionPerformed(evt);
            }
        });

        jToggleButtonposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonpositionActionPerformed(evt);
            }
        });

        jButtondown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/down.png"))); // NOI18N
        jButtondown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelgamepadLayout = new javax.swing.GroupLayout(jPanelgamepad);
        jPanelgamepad.setLayout(jPanelgamepadLayout);
        jPanelgamepadLayout.setHorizontalGroup(
            jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelgamepadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonleft, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtondown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonup, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jToggleButtonposition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonright, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelgamepadLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtondown, jButtonleft, jButtonright, jButtonup});

        jPanelgamepadLayout.setVerticalGroup(
            jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelgamepadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonleft, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonposition, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonright, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtondown, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelgamepadLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtondown, jButtonleft, jButtonright, jButtonup, jToggleButtonposition});

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setOpaque(false);
        jPanel9.setLayout(null);
        jPanel9.add(jLabel2);
        jLabel2.setBounds(10, 10, 230, 200);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jTextAreadisplay.setEditable(false);
        jTextAreadisplay.setColumns(20);
        jTextAreadisplay.setRows(5);
        jTextAreadisplay.setBorder(null);
        jTextAreadisplay.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreadisplay);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 230, 200);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelgamepad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelgamepad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setOpaque(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jMenuFile.setText("Juego");

        jMenuItemopen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemopen.setText("Abrir");
        jMenuItemopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemopenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemopen);

        jMenuItemnewgame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemnewgame.setText("Nuevo");
        jMenuItemnewgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemnewgameActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemnewgame);

        jMenuItemexportxml.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemexportxml.setText("Exportar a  XML");
        jMenuItemexportxml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemexportxmlActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemexportxml);

        jMenuItemexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemexit.setText("Salir");
        jMenuItemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemexitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemexit);

        jMenuBar1.add(jMenuFile);

        jMenuedit.setText("Editar");

        jMenuItemundo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemundo.setText("Deshacer");
        jMenuItemundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemundoActionPerformed(evt);
            }
        });
        jMenuedit.add(jMenuItemundo);

        jMenuItemreundo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemreundo.setText("Rehacer");
        jMenuItemreundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemreundoActionPerformed(evt);
            }
        });
        jMenuedit.add(jMenuItemreundo);

        jMenuItemmakegame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemmakegame.setText("Crear Juego");
        jMenuItemmakegame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemmakegameActionPerformed(evt);
            }
        });
        jMenuedit.add(jMenuItemmakegame);

        jMenuBar1.add(jMenuedit);

        jMenusetting.setText("Opciones");
        jMenusetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenusettingActionPerformed(evt);
            }
        });

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Preferencias");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenusetting.add(jMenuItem6);

        jMenuBar1.add(jMenusetting);

        jMenu5.setText("Ayuda");

        jMenuItem3.setText("jMenuItem3");
        jMenu5.add(jMenuItem3);

        jMenu4.setText("Acerca de");
        jMenu5.add(jMenu4);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonmoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmoveActionPerformed
      solitariochino.setcoordinatein(Integer.valueOf(jTextFieldxin.getText())-1, 
              Integer.valueOf(jTextFieldyin.getText())-1);
      solitariochino.setcoordinateout(Integer.valueOf(jTextFieldxout.getText())-1,
              Integer.valueOf(jTextFieldyout.getText())-1);
      solitariochino.setMove();
      jTextAreadisplay.setText("");
      jTextAreadisplay.setText(solitariochino.toString());
      jProgressBar1.setValue((solitariochino.getNumall()*100)/solitariochino.getAll());
    }//GEN-LAST:event_jButtonmoveActionPerformed

    private void jButtonundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonundoActionPerformed
        solitariochino.undoMove();
        jTextAreadisplay.setText("");
        jProgressBar1.setValue((solitariochino.getNumall()*100)/solitariochino.getAll());
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jButtonundoActionPerformed

    private void jMenuItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemexitActionPerformed
        this.closewindows();
    }//GEN-LAST:event_jMenuItemexitActionPerformed

    private void windowClosing(){
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent event ){
                closewindows();
            }});
    }
    private void closewindows(){
        if (JOptionPane.showConfirmDialog(this, "¿Desea salir del juego?",
                "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            
            if(JOptionPane.showConfirmDialog(this, "¿Desea guardar los datos?", "Aviso", 
                    JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                
                JOptionPane.showMessageDialog(this, "Se han guardado los datos.", "Información", JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
            }else{
                JOptionPane.showMessageDialog(this, "Los datos se perderán.", "Atención", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
    
    }
    private void jMenusettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenusettingActionPerformed
        
        jDialogsetting.setVisible(true);
        
    }//GEN-LAST:event_jMenusettingActionPerformed

    private void jMenuItemmakegameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemmakegameActionPerformed
        if(jLayeredPane2.isVisible()){
        jLayeredPane2.setVisible(false);
        jDesktopPane1.setVisible(true);
        jInternalFramecreategame.pack();
        jInternalFramecreategame.setClosable(true);
        jInternalFramecreategame.setResizable(true);
        jDesktopPane1.setSize(this.getSize());
        jDesktopPane1.add(jInternalFramecreategame);
        jInternalFramecreategame.setVisible(true);
        jMenuItemmakegame.setText("Cerrar Modo Crear");
        }else{
            try {
                jInternalFramecreategame.setVisible(false);
                jInternalFramecreategame.setClosed(true);
                jLayeredPane2.setVisible(true);
                jDesktopPane1.setVisible(false);
                jMenuItemmakegame.setText("Crear juego");
            } catch (PropertyVetoException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }      
                
    }//GEN-LAST:event_jMenuItemmakegameActionPerformed

    private void jMenuItemopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemopenActionPerformed

        JFileChooser selectfile = new JFileChooser();
        selectfile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        selectfile.setCurrentDirectory(new File(".", "Level"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos LEVEL (*.level)", "level");
        selectfile.setFileFilter(filter);
        selectfile.setSize(400, 400);
        if (selectfile.showOpenDialog(this)== JFileChooser.APPROVE_OPTION) {
            File file = selectfile.getSelectedFile();
            solitariochino.setFile(file);
            JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxlevel.setModel(new DefaultComboBoxModel(solitariochino.getListlevel()));
        } else {
            JOptionPane.showMessageDialog(this, "No se ha cargado archivo niveles.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemopenActionPerformed

    private void jMenuItemnewgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemnewgameActionPerformed
        solitariochino.generategame();
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jMenuItemnewgameActionPerformed

    private void jButtonexamine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexamine1ActionPerformed
        JFileChooser selectorfile = new JFileChooser();
        selectorfile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        selectorfile.setCurrentDirectory(new File(".", "Level"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos LEVEL (*.level)", "level");
        selectorfile.setFileFilter(filter);
        int selector = selectorfile.showOpenDialog(this);
        if (selector == JFileChooser.APPROVE_OPTION) {
            File file = selectorfile.getSelectedFile();
            solitariochino.setFile(file);
            JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxlevel.setModel(new DefaultComboBoxModel(solitariochino.getListlevel()));
        } else {
            JOptionPane.showMessageDialog(this, "No se ha cargado archivo niveles.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_jButtonexamine1ActionPerformed

    private void jComboBoxlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxlevelActionPerformed

    private void jMenuItemexportxmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemexportxmlActionPerformed

        JFileChooser selectfilesave = new JFileChooser();
        selectfilesave.setSize(400, 400);
        selectfilesave.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos XML (*.xml)", "xml");
        if (selectfilesave.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File dir = selectfilesave.getCurrentDirectory();
            if (JOptionPane.showConfirmDialog(this, "¿Se va a guardar el archivo?",
                    "Avertencia", JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
                try {
                    TransformerFactory madexml = TransformerFactory.newInstance();
                    Transformer madedocxml = madexml.newTransformer();
                    madedocxml.setOutputProperty(OutputKeys.INDENT, "yes");
                    madedocxml.setOutputProperty(OutputPropertiesFactory.S_KEY_INDENT_AMOUNT, "3");
                    Result writexml = new StreamResult(dir.getAbsolutePath() + "movimientos_de_partida.xml");
                    madedocxml.transform(solitariochino.generateXml(), writexml);
                    JOptionPane.showMessageDialog(null, "El documento XML se ha creado.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                } catch (TransformerConfigurationException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (TransformerException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.",
                        "Información.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Operación de guardado cancelada.",
                        "Avertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemexportxmlActionPerformed

    private void jButtonrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrightActionPerformed
       if(!jToggleButtonposition.isSelected()){
            solitariochino.setcoordinatein(solitariochino.coordinatexin, solitariochino.coordinateyin+1);
            jTextFieldyin.setText(String.valueOf(1+solitariochino.coordinateyin));
        }else{
            solitariochino.setcoordinateout(solitariochino.coordinatexout, solitariochino.coordinateyout+1);
            jTextFieldyout.setText(String.valueOf(1+solitariochino.coordinateyout));
        }
    }//GEN-LAST:event_jButtonrightActionPerformed

    private void jButtonundo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonundo1ActionPerformed
        solitariochino.reUndoMove();
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jButtonundo1ActionPerformed

    private void jMenuItemundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemundoActionPerformed
        solitariochino.undoMove();
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jMenuItemundoActionPerformed

    private void jButtonleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonleftActionPerformed
        if(!jToggleButtonposition.isSelected()){
            solitariochino.setcoordinatein(solitariochino.coordinatexin, solitariochino.coordinateyin-1);
            jTextFieldyin.setText(String.valueOf(1+solitariochino.coordinateyin));
        }else{
            solitariochino.setcoordinateout(solitariochino.coordinatexout, solitariochino.coordinateyout-1);
            jTextFieldyout.setText(String.valueOf(1+solitariochino.coordinateyout));
        }
    }//GEN-LAST:event_jButtonleftActionPerformed

    private void jMenuItemreundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemreundoActionPerformed
        solitariochino.reUndoMove();
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jMenuItemreundoActionPerformed

    private void jMenuItemreundomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemreundomenuActionPerformed
        jPopupMenu1.setVisible(false);
        solitariochino.undoMove();
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jMenuItemreundomenuActionPerformed

    private void jMenuItemrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemrefreshActionPerformed
        jPopupMenu1.setVisible(false);
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jMenuItemrefreshActionPerformed

    private void jMenuItemundomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemundomenuActionPerformed

        jPopupMenu1.setVisible(false);
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
        
    }//GEN-LAST:event_jMenuItemundomenuActionPerformed

    private void jMenusettingmenuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenusettingmenuFocusGained
       jMenusettingmenu.setPopupMenuVisible(true);
    }//GEN-LAST:event_jMenusettingmenuFocusGained

    private void jToggleButtonpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonpositionActionPerformed
        if(!jToggleButtonposition.isSelected()){
            jToggleButtonposition.setSelected(false);
            jToggleButtonposition.setText("Inicial");
        }else{
            jToggleButtonposition.setSelected(true);
            jToggleButtonposition.setText("Final");  
        }
    }//GEN-LAST:event_jToggleButtonpositionActionPerformed

    private void jButtonupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupActionPerformed
        if(!jToggleButtonposition.isSelected()){
            solitariochino.setcoordinatein(solitariochino.coordinatexin+1, solitariochino.coordinateyin);
            jTextFieldxin.setText(String.valueOf(1+solitariochino.coordinatexin));
        }else{
            solitariochino.setcoordinateout(solitariochino.coordinatexout+1, solitariochino.coordinateyout);
            jTextFieldxout.setText(String.valueOf(1+solitariochino.coordinateyout));
        }
    }//GEN-LAST:event_jButtonupActionPerformed

    private void jButtondownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondownActionPerformed
        if(!jToggleButtonposition.isSelected()){
            solitariochino.setcoordinatein(solitariochino.coordinatexin-1, solitariochino.coordinateyin);
            jTextFieldxin.setText(String.valueOf(1+solitariochino.coordinatexin));
        }else{
            solitariochino.setcoordinateout(solitariochino.coordinatexout-1, solitariochino.coordinateyout);
            jTextFieldxout.setText(String.valueOf(1+solitariochino.coordinateyout));
        }
    }//GEN-LAST:event_jButtondownActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        jDialogsetting.setVisible(true);
        jDialogsetting.setLocationRelativeTo(this);   
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jInternalFramecreategame.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemnewgame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemnewgame1ActionPerformed
        solitariochino.generategame();
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
    }//GEN-LAST:event_jMenuItemnewgame1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtondown;
    private javax.swing.JButton jButtonexamine1;
    private javax.swing.JButton jButtonleft;
    private javax.swing.JButton jButtonmove;
    private javax.swing.JButton jButtonright;
    private javax.swing.JButton jButtonundo;
    private javax.swing.JButton jButtonundo1;
    private javax.swing.JButton jButtonup;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox jComboBoxlevel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialogsetting;
    private javax.swing.JInternalFrame jInternalFramecreategame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemexit;
    private javax.swing.JMenuItem jMenuItemexportxml;
    private javax.swing.JMenuItem jMenuItemmakegame;
    private javax.swing.JMenuItem jMenuItemnewgame;
    private javax.swing.JMenuItem jMenuItemnewgame1;
    private javax.swing.JMenuItem jMenuItemopen;
    private javax.swing.JMenuItem jMenuItemrefresh;
    private javax.swing.JMenuItem jMenuItemreundo;
    private javax.swing.JMenuItem jMenuItemreundomenu;
    private javax.swing.JMenuItem jMenuItemundo;
    private javax.swing.JMenuItem jMenuItemundomenu;
    private javax.swing.JMenu jMenuedit;
    private javax.swing.JMenu jMenusetting;
    private javax.swing.JMenu jMenusettingmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelgamepad;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextAreadisplay;
    private javax.swing.JTextField jTextFieldxin;
    private javax.swing.JTextField jTextFieldxout;
    private javax.swing.JTextField jTextFieldyin;
    private javax.swing.JTextField jTextFieldyout;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButtonposition;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
