/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solitariochino;

import com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.transform.ErrorListener;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Templates;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.URIResolver;
import javax.xml.transform.stream.StreamResult;

/**
 *
 * @author Manuel Manzano López.
 */
public class main extends javax.swing.JFrame {
    
    Solitaire solitariochino=new Solitaire(3);

    
        
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButtonacept = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldxin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldyin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldxout = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldyout = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonmove = new javax.swing.JButton();
        jButtonundo = new javax.swing.JButton();
        jButtongeneratexml = new javax.swing.JButton();
        jButtonexamine = new javax.swing.JButton();
        jButtonload = new javax.swing.JButton();

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonacept.setText("Aceptar");
        jButtonacept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaceptActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("X in:");

        jLabel3.setText("Y in:");

        jLabel4.setText("X out:");

        jLabel5.setText("Y out:");

        jButtonmove.setText("Mover");
        jButtonmove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmoveActionPerformed(evt);
            }
        });

        jButtonundo.setText("Deshacer");
        jButtonundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonundoActionPerformed(evt);
            }
        });

        jButtongeneratexml.setText("Generate XML");
        jButtongeneratexml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongeneratexmlActionPerformed(evt);
            }
        });

        jButtonexamine.setText("Examinar...");
        jButtonexamine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexamineActionPerformed(evt);
            }
        });

        jButtonload.setText("Cargar");
        jButtonload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonundo)
                            .addGap(294, 294, 294))
                        .addComponent(jButtonmove, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonexamine)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonload)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonacept)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldxout)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldxin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldyout, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldyin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtongeneratexml))
                        .addContainerGap(208, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonmove)
                            .addComponent(jButtonacept)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldyin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldxin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldxout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldyout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jButtonundo)
                .addGap(18, 18, 18)
                .addComponent(jButtongeneratexml)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonexamine)
                    .addComponent(jButtonload))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonaceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaceptActionPerformed

        solitariochino.generategame();
        jTextArea1.setText("");
        jTextArea1.setText(solitariochino.toString());
    }//GEN-LAST:event_jButtonaceptActionPerformed

    private void jButtonmoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmoveActionPerformed
      solitariochino.setcoordinatein(Integer.valueOf(jTextFieldxin.getText())-1, 
              Integer.valueOf(jTextFieldyin.getText())-1);
      solitariochino.setcoordinateout(Integer.valueOf(jTextFieldxout.getText())-1,
              Integer.valueOf(jTextFieldyout.getText())-1);
      solitariochino.setMove();
      jTextArea1.setText("");
      jTextArea1.setText(solitariochino.toString());   
    }//GEN-LAST:event_jButtonmoveActionPerformed

    private void jButtonundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonundoActionPerformed
           solitariochino.undoMove();
           jTextArea1.setText("");
           jTextArea1.setText(solitariochino.toString());
     
    }//GEN-LAST:event_jButtonundoActionPerformed

    private void jButtongeneratexmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongeneratexmlActionPerformed
        try {
            TransformerFactory madexml = new TransformerFactory() {

                @Override
                public Transformer newTransformer(Source source) throws TransformerConfigurationException {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public Transformer newTransformer() throws TransformerConfigurationException {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public Templates newTemplates(Source source) throws TransformerConfigurationException {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public Source getAssociatedStylesheet(Source source, String media, String title, String charset) throws TransformerConfigurationException {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void setURIResolver(URIResolver resolver) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public URIResolver getURIResolver() {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void setFeature(String name, boolean value) throws TransformerConfigurationException {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public boolean getFeature(String name) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void setAttribute(String name, Object value) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public Object getAttribute(String name) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void setErrorListener(ErrorListener listener) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public ErrorListener getErrorListener() {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            };            
            Transformer madedocxml = madexml.newTransformer();
            madedocxml.setOutputProperty(OutputKeys.INDENT, "yes");
            madedocxml.setOutputProperty(OutputPropertiesFactory.S_KEY_INDENT_AMOUNT, "3");
            Result writexml= new StreamResult("movimientos_de_partida.xml");
            madedocxml.transform(solitariochino.generateXml(), writexml);
            JOptionPane.showMessageDialog(null, "El documento XML se ha creado.",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (TransformerConfigurationException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtongeneratexmlActionPerformed

    private void jButtonexamineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexamineActionPerformed
        
        JFileChooser selectorfile = new JFileChooser();
        selectorfile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        selectorfile.setCurrentDirectory(new File(".", "Level"));
        FileNameExtensionFilter filter= new FileNameExtensionFilter("Archivos LEVEL (*.level)","level" );
        selectorfile.setFileFilter(filter);
        int selector = selectorfile.showOpenDialog(this);
        if(selector==JFileChooser.APPROVE_OPTION){
            File file = selectorfile.getSelectedFile();
            solitariochino.setFile(file);
            JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.", 
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "No se ha cargado archivo niveles.", 
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonexamineActionPerformed

    private void jButtonloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloadActionPerformed
            
        
    }//GEN-LAST:event_jButtonloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonacept;
    private javax.swing.JButton jButtonexamine;
    private javax.swing.JButton jButtongeneratexml;
    private javax.swing.JButton jButtonload;
    private javax.swing.JButton jButtonmove;
    private javax.swing.JButton jButtonundo;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldxin;
    private javax.swing.JTextField jTextFieldxout;
    private javax.swing.JTextField jTextFieldyin;
    private javax.swing.JTextField jTextFieldyout;
    // End of variables declaration//GEN-END:variables
}
