/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solitariochino;

import com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory;
import java.awt.Dialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Result;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;

/**
 *
 * @author Manuel Manzano López.
 */
public class main extends javax.swing.JFrame {

    Solitaire solitariochino = new Solitaire(3);
    Calendar time = Calendar.getInstance();
    DataCSV savegame = new DataCSV(getClass().getResource("/Data/").getPath(),';');
    int[] startTime=null;
    Locale localES= new Locale("ES", "es");
    ResourceBundle bundle;
    
    
    

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icon.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        this.setTitle("Solitario Chino - Por defecto.");
        this.windowClosing();
        jToggleButtonposition.setSelected(false);
        jToggleButtonposition.setText("Inicial");
        jDialogsetting.setSize(500, 400);
        jLayeredPane2.setVisible(true);
        jDesktopPane1.setVisible(false);
        jCheckBoxMenuItemViewModeText.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogsetting = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPanesetting = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxlevel = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButtonexamine1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaPreview = new javax.swing.JTextArea();
        jTextFieldfile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelpreviewBackground = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabelcountry = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabellanguage = new javax.swing.JLabel();
        jButtonoksetting = new javax.swing.JButton();
        jButtoncancelsetting = new javax.swing.JButton();
        jInternalFramecreategame = new javax.swing.JInternalFrame();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenusettingmenu = new javax.swing.JMenu();
        jMenuItemnewgame1 = new javax.swing.JMenuItem();
        jMenuItemrefresh = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemundomenu = new javax.swing.JMenuItem();
        jMenuItemreundomenu = new javax.swing.JMenuItem();
        buttonGroupView = new javax.swing.ButtonGroup();
        buttonGrouplanguage = new javax.swing.ButtonGroup();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonundo = new javax.swing.JButton();
        jButtonundo1 = new javax.swing.JButton();
        jButtonmove = new javax.swing.JButton();
        jButtonrestart = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldxin = new javax.swing.JTextField();
        jTextFieldyin = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldxout = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldyout = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanelgamepad = new javax.swing.JPanel();
        jButtonleft = new javax.swing.JButton();
        jButtonup = new javax.swing.JButton();
        jButtonright = new javax.swing.JButton();
        jToggleButtonposition = new javax.swing.JToggleButton();
        jButtondown = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanelDisplayGraf = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreadisplay = new javax.swing.JTextArea();
        jLabelbackground = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemopen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemnewgame = new javax.swing.JMenuItem();
        jMenuItemrestart = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemsave = new javax.swing.JMenuItem();
        jMenuItemsaveAs = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemexportxml = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemexit = new javax.swing.JMenuItem();
        jMenuedit = new javax.swing.JMenu();
        jMenuItemundo = new javax.swing.JMenuItem();
        jMenuItemreundo = new javax.swing.JMenuItem();
        jMenuHistory = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemmakegame = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jCheckBoxMenuItemViewModeText = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemViewModeGraf = new javax.swing.JCheckBoxMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItemBackground = new javax.swing.JRadioButtonMenuItem();
        jMenusetting = new javax.swing.JMenu();
        jMenuItemsetting = new javax.swing.JMenuItem();
        jMenuhelp = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));

        jComboBoxlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxlevelActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Res/Bundle"); // NOI18N
        jLabel6.setText(bundle.getString("main.jLabel6.text")); // NOI18N

        jButtonexamine1.setText(bundle.getString("main.jButtonexamine1.text")); // NOI18N
        jButtonexamine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexamine1ActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), bundle.getString("main.jPanel11.border.title"))); // NOI18N

        jTextAreaPreview.setEditable(false);
        jTextAreaPreview.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaPreview.setColumns(20);
        jTextAreaPreview.setRows(5);
        jScrollPane3.setViewportView(jTextAreaPreview);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jLabel7.setText(bundle.getString("main.jLabel7.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonexamine1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxlevel, 0, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldfile))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonexamine1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPanesetting.addTab(bundle.getString("main.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jButton1.setText(bundle.getString("main.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelpreviewBackground.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabelpreviewBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabelpreviewBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab(bundle.getString("main.jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab(bundle.getString("main.jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        jTabbedPanesetting.addTab(bundle.getString("main.jTabbedPane3.TabConstraints.tabTitle"), jTabbedPane3); // NOI18N

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelcountry.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelcountry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcountry.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGrouplanguage.add(jRadioButton1);
        jRadioButton1.setText(bundle.getString("main.jRadioButton1.text")); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGrouplanguage.add(jRadioButton2);
        jRadioButton2.setText(bundle.getString("main.jRadioButton1.text")); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGrouplanguage.add(jRadioButton3);
        jRadioButton3.setText(bundle.getString("main.jRadioButton1.text")); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGrouplanguage.add(jRadioButton4);
        jRadioButton4.setText(bundle.getString("main.jRadioButton1.text")); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGrouplanguage.add(jRadioButton5);
        jRadioButton5.setText(bundle.getString("main.jRadioButton5.text")); // NOI18N
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel14);

        jLabellanguage.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabellanguage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabellanguage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabelcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabellanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanesetting.addTab(bundle.getString("main.jPanel12.TabConstraints.tabTitle"), jPanel12); // NOI18N

        jButtonoksetting.setText(bundle.getString("main.jButtonoksetting.text")); // NOI18N
        jButtonoksetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonoksettingActionPerformed(evt);
            }
        });

        jButtoncancelsetting.setText(bundle.getString("main.jButtoncancelsetting.text")); // NOI18N
        jButtoncancelsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelsettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPanesetting)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonoksetting)
                        .addGap(18, 18, 18)
                        .addComponent(jButtoncancelsetting)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanesetting, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonoksetting)
                    .addComponent(jButtoncancelsetting))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogsettingLayout = new javax.swing.GroupLayout(jDialogsetting.getContentPane());
        jDialogsetting.getContentPane().setLayout(jDialogsettingLayout);
        jDialogsettingLayout.setHorizontalGroup(
            jDialogsettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        jDialogsettingLayout.setVerticalGroup(
            jDialogsettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogsettingLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        jInternalFramecreategame.setVisible(true);

        jToolBar1.setRollover(true);

        jButton3.setText(bundle.getString("main.jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setText(bundle.getString("main.jButton4.text")); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setText(bundle.getString("main.jButton5.text")); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jScrollPane2.setViewportView(jTextPane1);

        jMenu6.setText(bundle.getString("main.jMenu6.text")); // NOI18N
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem2.setText(bundle.getString("main.jMenuItem2.text")); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar2.add(jMenu6);

        jMenu7.setText(bundle.getString("main.jMenu7.text")); // NOI18N

        jMenuItem4.setText(bundle.getString("main.jMenuItem4.text")); // NOI18N
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText(bundle.getString("main.jMenuItem5.text")); // NOI18N
        jMenu7.add(jMenuItem5);

        jMenuBar2.add(jMenu7);

        jMenu1.setText(bundle.getString("main.jMenu1.text")); // NOI18N

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText(bundle.getString("main.jCheckBoxMenuItem1.text")); // NOI18N
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuItem7.setText(bundle.getString("main.jMenuItem7.text")); // NOI18N
        jMenu1.add(jMenuItem7);

        jMenuBar2.add(jMenu1);

        jInternalFramecreategame.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFramecreategameLayout = new javax.swing.GroupLayout(jInternalFramecreategame.getContentPane());
        jInternalFramecreategame.getContentPane().setLayout(jInternalFramecreategameLayout);
        jInternalFramecreategameLayout.setHorizontalGroup(
            jInternalFramecreategameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramecreategameLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 383, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramecreategameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jInternalFramecreategameLayout.setVerticalGroup(
            jInternalFramecreategameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramecreategameLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPopupMenu1.setBorder(null);

        jMenusettingmenu.setText(bundle.getString("main.jMenusettingmenu.text")); // NOI18N
        jMenusettingmenu.setMinimumSize(new java.awt.Dimension(100, 100));
        jMenusettingmenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenusettingmenuFocusGained(evt);
            }
        });

        jMenuItemnewgame1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemnewgame1.setText(bundle.getString("main.jMenuItemnewgame1.text")); // NOI18N
        jMenuItemnewgame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemnewgame1ActionPerformed(evt);
            }
        });
        jMenusettingmenu.add(jMenuItemnewgame1);

        jMenuItemrefresh.setText(bundle.getString("main.jMenuItemrefresh.text")); // NOI18N
        jMenuItemrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemrefreshActionPerformed(evt);
            }
        });
        jMenusettingmenu.add(jMenuItemrefresh);

        jMenuItem1.setText(bundle.getString("main.jMenuItem1.text")); // NOI18N
        jMenusettingmenu.add(jMenuItem1);

        jPopupMenu1.add(jMenusettingmenu);
        jPopupMenu1.add(jSeparator6);

        jMenuItemundomenu.setText(bundle.getString("main.jMenuItemundomenu.text")); // NOI18N
        jMenuItemundomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemundomenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemundomenu);

        jMenuItemreundomenu.setText(bundle.getString("main.jMenuItemreundomenu.text")); // NOI18N
        jMenuItemreundomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemreundomenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemreundomenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setComponentPopupMenu(jPopupMenu1);
        jPanel1.setOpaque(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/undo.png"))); // NOI18N
        jButtonundo.setToolTipText(bundle.getString("main.jButtonundo.toolTipText")); // NOI18N
        jButtonundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonundoActionPerformed(evt);
            }
        });

        jButtonundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reundo.png"))); // NOI18N
        jButtonundo1.setToolTipText(bundle.getString("main.jButtonundo1.toolTipText")); // NOI18N
        jButtonundo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonundo1ActionPerformed(evt);
            }
        });

        jButtonmove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/move.png"))); // NOI18N
        jButtonmove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmoveActionPerformed(evt);
            }
        });

        jButtonrestart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reboot.png"))); // NOI18N
        jButtonrestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrestartActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("main.jPanel7.border.title"))); // NOI18N

        jLabel1.setText(bundle.getString("main.jLabel1.text")); // NOI18N

        jLabel3.setText(bundle.getString("main.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldxin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldyin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldyin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldxin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("main.jPanel8.border.title"))); // NOI18N

        jLabel4.setText(bundle.getString("main.jLabel4.text")); // NOI18N

        jLabel5.setText(bundle.getString("main.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldxout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldyout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldxout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldyout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("main.jPanel10.border.title"))); // NOI18N

        jProgressBar1.setForeground(new java.awt.Color(0, 255, 0));
        jProgressBar1.setToolTipText(bundle.getString("main.jProgressBar1.toolTipText")); // NOI18N
        jProgressBar1.setOpaque(true);
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonmove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonundo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonundo))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonrestart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonundo1)
                    .addComponent(jButtonundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonrestart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonmove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelgamepad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelgamepad.setOpaque(false);

        jButtonleft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left.png"))); // NOI18N
        jButtonleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonleftActionPerformed(evt);
            }
        });

        jButtonup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/up.png"))); // NOI18N
        jButtonup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupActionPerformed(evt);
            }
        });

        jButtonright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/right.png"))); // NOI18N
        jButtonright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrightActionPerformed(evt);
            }
        });

        jToggleButtonposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonpositionActionPerformed(evt);
            }
        });

        jButtondown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/down.png"))); // NOI18N
        jButtondown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelgamepadLayout = new javax.swing.GroupLayout(jPanelgamepad);
        jPanelgamepad.setLayout(jPanelgamepadLayout);
        jPanelgamepadLayout.setHorizontalGroup(
            jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelgamepadLayout.createSequentialGroup()
                .addComponent(jButtonleft, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtondown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonup, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jToggleButtonposition, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonright, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanelgamepadLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtondown, jButtonleft, jButtonright, jButtonup});

        jPanelgamepadLayout.setVerticalGroup(
            jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelgamepadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelgamepadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonleft, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonposition, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonright, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtondown, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelgamepadLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtondown, jButtonleft, jButtonright, jButtonup, jToggleButtonposition});

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setOpaque(false);
        jPanel9.setLayout(null);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jTextAreadisplay.setEditable(false);
        jTextAreadisplay.setColumns(20);
        jTextAreadisplay.setRows(5);
        jTextAreadisplay.setBorder(null);
        jTextAreadisplay.setComponentPopupMenu(jPopupMenu1);
        jTextAreadisplay.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreadisplay);

        javax.swing.GroupLayout jPanelDisplayGrafLayout = new javax.swing.GroupLayout(jPanelDisplayGraf);
        jPanelDisplayGraf.setLayout(jPanelDisplayGrafLayout);
        jPanelDisplayGrafLayout.setHorizontalGroup(
            jPanelDisplayGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanelDisplayGrafLayout.setVerticalGroup(
            jPanelDisplayGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisplayGrafLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPanelDisplayGraf);
        jPanelDisplayGraf.setBounds(10, 10, 230, 200);

        jLabelbackground.setComponentPopupMenu(jPopupMenu1);
        jPanel9.add(jLabelbackground);
        jLabelbackground.setBounds(10, 10, 220, 200);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelgamepad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelgamepad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setOpaque(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuFile.setText(bundle.getString("main.jMenuFile.text")); // NOI18N

        jMenuItemopen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemopen.setText(bundle.getString("main.jMenuItemopen.text")); // NOI18N
        jMenuItemopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemopenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemopen);
        jMenuFile.add(jSeparator1);

        jMenuItemnewgame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemnewgame.setText(bundle.getString("main.jMenuItemnewgame.text")); // NOI18N
        jMenuItemnewgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemnewgameActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemnewgame);

        jMenuItemrestart.setText(bundle.getString("main.jMenuItemrestart.text")); // NOI18N
        jMenuFile.add(jMenuItemrestart);
        jMenuFile.add(jSeparator2);

        jMenuItemsave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemsave.setText(bundle.getString("main.jMenuItemsave.text")); // NOI18N
        jMenuItemsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemsave);

        jMenuItemsaveAs.setText(bundle.getString("main.jMenuItemsaveAs.text")); // NOI18N
        jMenuItemsaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemsaveAs);
        jMenuFile.add(jSeparator4);

        jMenuItemexportxml.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemexportxml.setText(bundle.getString("main.jMenuItemexportxml.text")); // NOI18N
        jMenuItemexportxml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemexportxmlActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemexportxml);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem12.setText(bundle.getString("main.jMenuItem12.text")); // NOI18N
        jMenuFile.add(jMenuItem12);
        jMenuFile.add(jSeparator3);

        jMenuItemexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemexit.setText(bundle.getString("main.jMenuItemexit.text")); // NOI18N
        jMenuItemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemexitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemexit);

        jMenuBar1.add(jMenuFile);

        jMenuedit.setText(bundle.getString("main.jMenuedit.text")); // NOI18N

        jMenuItemundo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemundo.setText(bundle.getString("main.jMenuItemundo.text")); // NOI18N
        jMenuItemundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemundoActionPerformed(evt);
            }
        });
        jMenuedit.add(jMenuItemundo);

        jMenuItemreundo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemreundo.setText(bundle.getString("main.jMenuItemreundo.text")); // NOI18N
        jMenuItemreundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemreundoActionPerformed(evt);
            }
        });
        jMenuedit.add(jMenuItemreundo);

        jMenuHistory.setText(bundle.getString("main.jMenuHistory.text")); // NOI18N
        jMenuHistory.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
                jMenuHistoryMenuDragMouseEntered(evt);
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });
        jMenuHistory.add(jMenuItem3);

        jMenuedit.add(jMenuHistory);
        jMenuedit.add(jSeparator5);

        jMenuItemmakegame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemmakegame.setText(bundle.getString("main.jMenuItemmakegame.text")); // NOI18N
        jMenuItemmakegame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemmakegameActionPerformed(evt);
            }
        });
        jMenuedit.add(jMenuItemmakegame);

        jMenuBar1.add(jMenuedit);

        jMenuView.setText(bundle.getString("main.jMenuView.text")); // NOI18N

        buttonGroupView.add(jCheckBoxMenuItemViewModeText);
        jCheckBoxMenuItemViewModeText.setSelected(true);
        jCheckBoxMenuItemViewModeText.setText(bundle.getString("main.jCheckBoxMenuItemViewModeText.text")); // NOI18N
        jCheckBoxMenuItemViewModeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemViewModeTextActionPerformed(evt);
            }
        });
        jMenuView.add(jCheckBoxMenuItemViewModeText);

        buttonGroupView.add(jCheckBoxMenuItemViewModeGraf);
        jCheckBoxMenuItemViewModeGraf.setText(bundle.getString("main.jCheckBoxMenuItemViewModeGraf.text")); // NOI18N
        jCheckBoxMenuItemViewModeGraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemViewModeGrafActionPerformed(evt);
            }
        });
        jMenuView.add(jCheckBoxMenuItemViewModeGraf);
        jMenuView.add(jSeparator7);

        jRadioButtonMenuItemBackground.setSelected(true);
        jRadioButtonMenuItemBackground.setText(bundle.getString("main.jRadioButtonMenuItemBackground.text")); // NOI18N
        jRadioButtonMenuItemBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemBackgroundActionPerformed(evt);
            }
        });
        jMenuView.add(jRadioButtonMenuItemBackground);

        jMenuBar1.add(jMenuView);

        jMenusetting.setText(bundle.getString("main.jMenusetting.text")); // NOI18N

        jMenuItemsetting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemsetting.setText(bundle.getString("main.jMenuItemsetting.text")); // NOI18N
        jMenuItemsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsettingActionPerformed(evt);
            }
        });
        jMenusetting.add(jMenuItemsetting);

        jMenuBar1.add(jMenusetting);

        jMenuhelp.setText(bundle.getString("main.jMenuhelp.text")); // NOI18N

        jMenu2.setText(bundle.getString("main.jMenu2.text")); // NOI18N

        jMenuItem10.setText(bundle.getString("main.jMenuItem10.text")); // NOI18N
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText(bundle.getString("main.jMenuItem11.text")); // NOI18N
        jMenu2.add(jMenuItem11);

        jMenuhelp.add(jMenu2);

        jMenu4.setText(bundle.getString("main.jMenu4.text")); // NOI18N
        jMenuhelp.add(jMenu4);

        jMenuBar1.add(jMenuhelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonmoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmoveActionPerformed
        solitariochino.setcoordinatein(Integer.valueOf(jTextFieldxin.getText()) - 1,
                Integer.valueOf(jTextFieldyin.getText()) - 1);
        solitariochino.setcoordinateout(Integer.valueOf(jTextFieldxout.getText()) - 1,
                Integer.valueOf(jTextFieldyout.getText()) - 1);
        solitariochino.setMove();
        this.refreshDisplay();
    }//GEN-LAST:event_jButtonmoveActionPerformed

    private void jButtonundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonundoActionPerformed
        solitariochino.undoMove();
        this.refreshDisplay();
    }//GEN-LAST:event_jButtonundoActionPerformed

    private void jMenuItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemexitActionPerformed
        this.closewindows();
    }//GEN-LAST:event_jMenuItemexitActionPerformed

    private void windowClosing() {
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent event) {
                closewindows();
            }
        });
    }
    
    private void closewindows() {
        if (JOptionPane.showConfirmDialog(this, "¿Desea salir del juego?",
                "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            if (JOptionPane.showConfirmDialog(this, "¿Desea guardar los datos?", "Aviso",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    savegame.setData(this.startTime,
                            solitariochino.getAll()-solitariochino.getNumall(),
                            String.valueOf(jComboBoxlevel.getSelectedItem()),
                            this.getTimeStart());
                JOptionPane.showMessageDialog(this, "Se han guardado los datos.", "Información", JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, "Los datos se perderán.", "Atención", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }

    }
    private void jMenuItemmakegameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemmakegameActionPerformed
        if (jPanel1.isVisible()) {
            jPanel1.setVisible(false);
            jDesktopPane1.setVisible(true);
            jDesktopPane1.setSize(800, 600);
            jInternalFramecreategame.pack();
            jInternalFramecreategame.setSize(200, 200);
            jInternalFramecreategame.setClosable(true);
            jInternalFramecreategame.setResizable(true);
            jDesktopPane1.setSize(this.getSize());
            jDesktopPane1.add(jInternalFramecreategame);
            jInternalFramecreategame.setVisible(true);
            jMenuItemmakegame.setText("Cerrar Modo Crear");
        } else {
            try {
                jInternalFramecreategame.setVisible(false);
                jInternalFramecreategame.setClosed(true);
                jPanel1.setVisible(true);
                jDesktopPane1.setVisible(false);
                jMenuItemmakegame.setText("Crear juego");
            } catch (PropertyVetoException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jMenuItemmakegameActionPerformed

    private void jMenuItemopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemopenActionPerformed

        JFileChooser selectfile = new JFileChooser();
        selectfile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        selectfile.setCurrentDirectory(new File(".", "Level"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos LEVEL (*.level)", "level");
        selectfile.setFileFilter(filter);
        selectfile.setSize(400, 400);
        if (selectfile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = selectfile.getSelectedFile();
            solitariochino.setFile(file);
            JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxlevel.setModel(new DefaultComboBoxModel(solitariochino.getListlevel()));
        } else {
            JOptionPane.showMessageDialog(this, "No se ha cargado archivo niveles.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemopenActionPerformed

    private void jMenuItemnewgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemnewgameActionPerformed
        if (!solitariochino.isFileNull()) {
            solitariochino.generategame();
            jComboBoxlevel.setModel(new DefaultComboBoxModel(new String[]{"Default"}));
            jComboBoxlevel.setSelectedIndex(0);
            jTextAreaPreview.setText(solitariochino.toString());
        } else {
            solitariochino.setLevel(jComboBoxlevel.getSelectedIndex() + 1);
        }
        solitariochino.setDefault();
        this.refreshDisplay();
        this.startTime = this.getTimeStart();
    }//GEN-LAST:event_jMenuItemnewgameActionPerformed
    /**
     * 
     * @return 
     */
    private int[] getTimeStart(){
        int [] tmp={time.get(Calendar.YEAR),time.get(Calendar.MONTH),
        time.get(Calendar.DAY_OF_MONTH),time.get(Calendar.HOUR),time.get(Calendar.MINUTE)
                ,time.get(Calendar.SECOND)};
        return tmp;
    }
    private String getTimeStartString(){
        
        return String.valueOf(this.getTimeStart()[0]+'-'+this.getTimeStart()[1]+
                '-'+this.getTimeStart()[2]);
    }

    private void jButtonexamine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexamine1ActionPerformed
        JFileChooser selectorfile = new JFileChooser();
        selectorfile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        selectorfile.setCurrentDirectory(new File(".", "Level"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos LEVEL (*.level)", "level");
        selectorfile.setFileFilter(filter);
        if (selectorfile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = selectorfile.getSelectedFile();
            solitariochino.setFile(file);
            JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxlevel.setModel(new DefaultComboBoxModel(solitariochino.getListlevel()));
            jTextFieldfile.setText(file.getAbsolutePath());
        } else {
            JOptionPane.showMessageDialog(this, "No se ha cargado archivo niveles.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonexamine1ActionPerformed

    private void jComboBoxlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxlevelActionPerformed
       if(solitariochino.isFileNull()){
            solitariochino.setLevel(jComboBoxlevel.getSelectedIndex()+1);  
            jTextAreaPreview.setText(solitariochino.toString());
       }
        
    }//GEN-LAST:event_jComboBoxlevelActionPerformed

    private void jMenuItemexportxmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemexportxmlActionPerformed

        JFileChooser selectfilesave = new JFileChooser();
        selectfilesave.setSize(400, 400);
        selectfilesave.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos XML (*.xml)", "xml");
        selectfilesave.setFileFilter(filter);
        if (selectfilesave.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            
            if (JOptionPane.showConfirmDialog(this, "¿Se va a guardar el archivo?",
                    "Avertencia", JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
                File dir = selectfilesave.getSelectedFile();
                try {
                    TransformerFactory madexml = TransformerFactory.newInstance();
                    Transformer madedocxml = madexml.newTransformer();
                    madedocxml.setOutputProperty(OutputKeys.INDENT, "yes");
                    madedocxml.setOutputProperty(OutputPropertiesFactory.S_KEY_INDENT_AMOUNT, "3");
                    Result writexml = new StreamResult(dir.getAbsoluteFile()+"\\movimientos_de_partida.xml");
                    madedocxml.transform(solitariochino.generateXml(), writexml);
                    JOptionPane.showMessageDialog(null, "El documento XML se ha creado.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                } catch (TransformerConfigurationException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (TransformerException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.",
                        "Información.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Operación de guardado cancelada.",
                        "Avertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemexportxmlActionPerformed

    private void jButtonrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrightActionPerformed
        solitariochino.setMoveRight(jToggleButtonposition.isSelected());
        jTextFieldyin.setText(String.valueOf(1 + solitariochino.getCoordinatexin()));
        jTextFieldyout.setText(String.valueOf(1 + solitariochino.getCoordinateyout()));

    }//GEN-LAST:event_jButtonrightActionPerformed

    private void jButtonundo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonundo1ActionPerformed
        this.jMenuItemundoActionPerformed(evt);    
    }//GEN-LAST:event_jButtonundo1ActionPerformed

    private void jMenuItemundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemundoActionPerformed
        this.jMenuItemreundoActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemundoActionPerformed

    private void jButtonleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonleftActionPerformed

        solitariochino.setMoveleft(jToggleButtonposition.isSelected());
        jTextFieldyin.setText(String.valueOf(1 + solitariochino.getCoordinateyin()));
        jTextFieldyout.setText(String.valueOf(1 + solitariochino.getCoordinateyout()));
    }//GEN-LAST:event_jButtonleftActionPerformed

    private void jMenuItemreundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemreundoActionPerformed
        solitariochino.reUndoMove();
        this.refreshDisplay();
        jProgressBar1.setValue((solitariochino.getNumall() * 100) / solitariochino.getAll());
    }//GEN-LAST:event_jMenuItemreundoActionPerformed

    private void jMenuItemreundomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemreundomenuActionPerformed
        jPopupMenu1.setVisible(false);
        this.jMenuItemreundoActionPerformed(evt); 
    }//GEN-LAST:event_jMenuItemreundomenuActionPerformed

    private void jMenuItemrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemrefreshActionPerformed

          jPopupMenu1.setVisible(false);
          this.refreshDisplay();
    }//GEN-LAST:event_jMenuItemrefreshActionPerformed

    private void jMenuItemundomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemundomenuActionPerformed

        jPopupMenu1.setVisible(false);
        this.jMenuItemundoActionPerformed(evt); 

    }//GEN-LAST:event_jMenuItemundomenuActionPerformed

    private void jMenusettingmenuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenusettingmenuFocusGained
        jMenusettingmenu.setPopupMenuVisible(true);
    }//GEN-LAST:event_jMenusettingmenuFocusGained

    private void jToggleButtonpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonpositionActionPerformed
        if (!jToggleButtonposition.isSelected()) {
            jButtonup.setIcon(new ImageIcon(getClass().getResource("/Imagenes/up.png")));
            jButtondown.setIcon(new ImageIcon(getClass().getResource("/Imagenes/down.png")));
            jButtonleft.setIcon(new ImageIcon(getClass().getResource("/Imagenes/left.png")));
            jButtonright.setIcon(new ImageIcon(getClass().getResource("/Imagenes/right.png")));
            jToggleButtonposition.setSelected(false);
            jToggleButtonposition.setText("Inicial");
        } else {
            jButtonup.setIcon(new ImageIcon(getClass().getResource("/Imagenes/up1.png")));
            jButtondown.setIcon(new ImageIcon(getClass().getResource("/Imagenes/down1.png")));
            jButtonleft.setIcon(new ImageIcon(getClass().getResource("/Imagenes/left1.png")));
            jButtonright.setIcon(new ImageIcon(getClass().getResource("/Imagenes/right1.png")));
            jToggleButtonposition.setSelected(true);
            jToggleButtonposition.setText("Final");
        }
    }//GEN-LAST:event_jToggleButtonpositionActionPerformed

    private void jButtonupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupActionPerformed
        solitariochino.setMoveUp(jToggleButtonposition.isSelected());
        jTextFieldxin.setText(String.valueOf(1 + solitariochino.getCoordinatexin()));
        jTextFieldxout.setText(String.valueOf(1 + solitariochino.getCoordinatexout()));
    }//GEN-LAST:event_jButtonupActionPerformed

    private void jButtondownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondownActionPerformed
        solitariochino.setMoveDown(jToggleButtonposition.isSelected());
        jTextFieldxin.setText(String.valueOf(1 + solitariochino.getCoordinatexin()));
        jTextFieldxout.setText(String.valueOf(1 + solitariochino.getCoordinatexout()));
        
    }//GEN-LAST:event_jButtondownActionPerformed

    private void jMenuItemsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsettingActionPerformed
        solitariochino.saveStatusBoard();
        jDialogsetting.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemsettingActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jInternalFramecreategame.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemnewgame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemnewgame1ActionPerformed
        this.jMenuItemnewgameActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemnewgame1ActionPerformed

    private void jMenuItemsaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsaveAsActionPerformed
        JFileChooser selectorfile = new JFileChooser();
        selectorfile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos CSV (*.csv)", "csv");
        selectorfile.setFileFilter(filter);
        if (selectorfile.showOpenDialog(this)== JFileChooser.APPROVE_OPTION) {
            File file = selectorfile.getSelectedFile();
            if(file.isDirectory()){
                file=new File(file, this.getTimeStartString()+".csv");
            }
            this.savegame.setname(file.getName());
            
            JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha guardado.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemsaveAsActionPerformed

    private void jCheckBoxMenuItemViewModeGrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemViewModeGrafActionPerformed
        this.setMode();
    }//GEN-LAST:event_jCheckBoxMenuItemViewModeGrafActionPerformed

    private void jCheckBoxMenuItemViewModeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemViewModeTextActionPerformed
         this.setMode();
    }//GEN-LAST:event_jCheckBoxMenuItemViewModeTextActionPerformed
    /**
     * Procedimiento para alternar los modos de visualización.
     * Texto o gráfico, menu item check box en un grupo de botones.
     */
    private void setMode(){
           jTextAreadisplay.setVisible(jCheckBoxMenuItemViewModeText.isSelected());
           jPanelDisplayGraf.setVisible(jCheckBoxMenuItemViewModeGraf.isSelected());
    }
    
    private void jRadioButtonMenuItemBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemBackgroundActionPerformed
        if(jRadioButtonMenuItemBackground.isSelected()){
            jLabelbackground.setIcon(new ImageIcon(getClass().getResource("")));
        }
    }//GEN-LAST:event_jRadioButtonMenuItemBackgroundActionPerformed

    private void jButtonoksettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonoksettingActionPerformed
        solitariochino.setDefault();
        jDialogsetting.setVisible(false);
        this.refreshDisplay();   
    }//GEN-LAST:event_jButtonoksettingActionPerformed

    private void jButtonrestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrestartActionPerformed
        solitariochino.setLevel(jComboBoxlevel.getSelectedIndex());
        this.refreshDisplay(); 
        this.startTime=this.getTimeStart();
        savegame.setData(this.startTime,
                            solitariochino.getAll()-solitariochino.getNumall(),
                            solitariochino.getListlevel()[jComboBoxlevel.getSelectedIndex()],
                            this.getTimeStart());
        solitariochino.setDefault();
        solitariochino.setLevel(jComboBoxlevel.getSelectedIndex()+1);   
    }//GEN-LAST:event_jButtonrestartActionPerformed

    private void jMenuItemsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsaveActionPerformed

        try {
            FileWriter fileWriter = new FileWriter(new File( savegame.setData(this.startTime,
                    solitariochino.getAll()-solitariochino.getNumall(),
                    String.valueOf(jComboBoxlevel.getSelectedItem()),
                    this.getTimeStart()).getName()));
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser selectfile = new JFileChooser();
        selectfile.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        selectfile.setCurrentDirectory(new File(".", "Level"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos LEVEL (*.png,*.jpg)", "png","jpg");
        selectfile.setFileFilter(filter);
        selectfile.setSize(400, 400);
        if (selectfile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file=selectfile.getSelectedFile();
            jLabelpreviewBackground.setIcon(new ImageIcon(file.getAbsolutePath()));
            System.out.println(file.getAbsolutePath());
            JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(this, "No se ha cargado archivo niveles.",
                    "Información.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuHistoryMenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_jMenuHistoryMenuDragMouseEntered
        if (solitariochino.gethistory().size() > 0) {
            jMenuHistory.removeAll();
            jMenuHistory.setEnabled(true);
            jMenuHistory.add(new JMenuItem(solitariochino.gethistory().get(0).toString()));
        } else {
            jMenuHistory.setEnabled(false);
        }

    }//GEN-LAST:event_jMenuHistoryMenuDragMouseEntered

    private void jButtoncancelsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelsettingActionPerformed
        solitariochino.restoreStatusBoard();
        jDialogsetting.setVisible(false);
        this.refreshDisplay();
    }//GEN-LAST:event_jButtoncancelsettingActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        this.setlanguaje(localES);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        this.setlanguaje(Locale.ENGLISH);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        this.setlanguaje(Locale.FRENCH);
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        this.setlanguaje(Locale.GERMAN);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        this.setlanguaje(Locale.ITALIAN);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    /**
     * Método para actualizar el elemento que muestra.
     */
    private void refreshDisplay(){
        jProgressBar1.setValue((solitariochino.getNumall() * 100) / solitariochino.getAll());
        jTextAreadisplay.setText("");
        jTextAreadisplay.setText(solitariochino.toString());
//        jPanelDisplayGraf.removeAll();
//        solitariochino.toGraphics(jPanelDisplayGraf);
        
    }
    
    private void setlanguaje(Locale local){
        this.setLocale(local);
        bundle=ResourceBundle.getBundle(getClass().getResource("/Res/Bundle").getFile(), local);
        this.initComponents();
        this.jLabelcountry.setText(this.getLocale().getDisplayCountry());
        this.jLabellanguage.setText(this.getLocale().getDisplayCountry());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupView;
    private javax.swing.ButtonGroup buttonGrouplanguage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtoncancelsetting;
    private javax.swing.JButton jButtondown;
    private javax.swing.JButton jButtonexamine1;
    private javax.swing.JButton jButtonleft;
    private javax.swing.JButton jButtonmove;
    private javax.swing.JButton jButtonoksetting;
    private javax.swing.JButton jButtonrestart;
    private javax.swing.JButton jButtonright;
    private javax.swing.JButton jButtonundo;
    private javax.swing.JButton jButtonundo1;
    private javax.swing.JButton jButtonup;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemViewModeGraf;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemViewModeText;
    private javax.swing.JComboBox jComboBoxlevel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialogsetting;
    private javax.swing.JInternalFrame jInternalFramecreategame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelbackground;
    private javax.swing.JLabel jLabelcountry;
    private javax.swing.JLabel jLabellanguage;
    private javax.swing.JLabel jLabelpreviewBackground;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHistory;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemexit;
    private javax.swing.JMenuItem jMenuItemexportxml;
    private javax.swing.JMenuItem jMenuItemmakegame;
    private javax.swing.JMenuItem jMenuItemnewgame;
    private javax.swing.JMenuItem jMenuItemnewgame1;
    private javax.swing.JMenuItem jMenuItemopen;
    private javax.swing.JMenuItem jMenuItemrefresh;
    private javax.swing.JMenuItem jMenuItemrestart;
    private javax.swing.JMenuItem jMenuItemreundo;
    private javax.swing.JMenuItem jMenuItemreundomenu;
    private javax.swing.JMenuItem jMenuItemsave;
    private javax.swing.JMenuItem jMenuItemsaveAs;
    private javax.swing.JMenuItem jMenuItemsetting;
    private javax.swing.JMenuItem jMenuItemundo;
    private javax.swing.JMenuItem jMenuItemundomenu;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JMenu jMenuedit;
    private javax.swing.JMenu jMenuhelp;
    private javax.swing.JMenu jMenusetting;
    private javax.swing.JMenu jMenusettingmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDisplayGraf;
    private javax.swing.JPanel jPanelgamepad;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemBackground;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPanesetting;
    private javax.swing.JTextArea jTextAreaPreview;
    private javax.swing.JTextArea jTextAreadisplay;
    private javax.swing.JTextField jTextFieldfile;
    private javax.swing.JTextField jTextFieldxin;
    private javax.swing.JTextField jTextFieldxout;
    private javax.swing.JTextField jTextFieldyin;
    private javax.swing.JTextField jTextFieldyout;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButtonposition;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
