/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frecuenciadecalificaciones;

/**
 *
 * @author Manuel Manzano López
 */
public class main extends javax.swing.JFrame {

    int tamaño = 0;
    int i=0;
    int[] calificaciones;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        jTextFieldcalificaciones.setEnabled(false);
        jButtonguardar.setEnabled(false);
        jButtonmostrar.setEnabled(false);
        jTextArearesultado.setEnabled(false);
        getRootPane().setDefaultButton(jButton1);
        jTextArearesultado.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldnumcalificacicones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldcalificaciones = new javax.swing.JTextField();
        jButtonguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArearesultado = new javax.swing.JTextArea();
        jButtonmostrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de calificaciones:");

        jTextFieldnumcalificacicones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldnumcalificaciconesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnumcalificaciconesKeyTyped(evt);
            }
        });

        jLabel2.setText("Introduce las calificaciones:");

        jTextFieldcalificaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldcalificacionesKeyTyped(evt);
            }
        });

        jButtonguardar.setText("Guardar");
        jButtonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguardarActionPerformed(evt);
            }
        });

        jTextArearesultado.setColumns(20);
        jTextArearesultado.setRows(5);
        jScrollPane1.setViewportView(jTextArearesultado);

        jButtonmostrar.setText("Mostrar");
        jButtonmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmostrarActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldcalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnumcalificacicones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonguardar)
                        .addComponent(jButtonmostrar))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonmostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldnumcalificacicones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonguardar)
                            .addComponent(jTextFieldcalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnumcalificaciconesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumcalificaciconesKeyTyped

        
    }//GEN-LAST:event_jTextFieldnumcalificaciconesKeyTyped

    private void jTextFieldcalificacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcalificacionesKeyTyped
        jButtonguardar.setEnabled(true);
    }//GEN-LAST:event_jTextFieldcalificacionesKeyTyped

    private void jButtonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguardarActionPerformed
        if(i<calificaciones.length){
            calificaciones[i]=Integer.valueOf(jTextFieldcalificaciones.getText());
            i++;
            jTextFieldcalificaciones.setText("");
             if(i>=calificaciones.length){
                 jButtonguardar.setEnabled(false);
                 jButtonmostrar.setEnabled(true);
                 jTextArearesultado.setEnabled(true);
             }
        }else{
            jTextFieldcalificaciones.setFocusable(true);
            getRootPane().setDefaultButton(jButtonmostrar);
        }
    }//GEN-LAST:event_jButtonguardarActionPerformed

    private void jButtonmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmostrarActionPerformed
        int aux=0;
        int tmp=0;
        while(aux<=10){
                tmp=0;
                for(int x=0;x<calificaciones.length;x++){
                    
                    if(calificaciones[x]==aux){
                        tmp++;
                    }
                }
                if(tmp>0){
                    jTextArearesultado.append("La calificación de "+aux+
                            " se repite "+ tmp+" veces.\n");
                }
            aux++;
        }
    }//GEN-LAST:event_jButtonmostrarActionPerformed

    private void jTextFieldnumcalificaciconesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumcalificaciconesKeyReleased

    }//GEN-LAST:event_jTextFieldnumcalificaciconesKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tamaño = Integer.valueOf(jTextFieldnumcalificacicones.getText());
        jTextFieldcalificaciones.setEnabled(true);
        calificaciones= new int[tamaño];
        i=0;
        getRootPane().setDefaultButton(jButtonguardar);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonguardar;
    private javax.swing.JButton jButtonmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArearesultado;
    private javax.swing.JTextField jTextFieldcalificaciones;
    private javax.swing.JTextField jTextFieldnumcalificacicones;
    // End of variables declaration//GEN-END:variables
}
